name = "AoC-2025"
version = "0.1.0"
defaultTargets = ["AoC2025"]

[[lean_lib]]
name = "AoC2025"

[[lean_exe]]
name = "day01"
root = "AoC2025.Day01"

[[lean_exe]]
name = "day02"
root = "AoC2025.Day02"

[[lean_exe]]
name = "day03"
root = "AoC2025.Day03"

[[lean_exe]]
name = "day04"
root = "AoC2025.Day04"

[[lean_exe]]
name = "day05"
root = "AoC2025.Day05"
